### PR TITLE
Add non-smoking notice

### PR DESCRIPTION
**Pull request by corwinc**
Fixes https://jira.openlattice.com/browse/LATTICE-373.

Adds notice of non-smoking policy & corresponding checkbox for nurse to note that patient was notified.

In order for checkbox val to be saved, data model needs to be updated.

### CODE REVIEW

**Comment by UnsungHero97** [comment]
Regarding "In order for checkbox val to be saved, data model needs to be updated", does that mean this PR is blocked by data model changes?

**Comment by corwinc** [comment]
Right, this is blocked by the data model update, but only if we want to save that value to the db. If not, we should be able to merge it. Seems like something that may not be of interest after form submission, rather just a simple acknowledgement for the nurse/CNA.

**Comment by kengie** [comment]
@moepstein, do you think we should save this in the data model, or in the Milestone datasets somewhere? See Corwin's comment above.

**Comment by moepstein** [comment]
Good question. Yes; we should save this in the data model - at some point, we will likely end up with a lot of facility information, so facility and facility policy information will be good to model. We can't rule out that patients' nicotine addictions impact their ability to successfully complete rehab.

**Comment by corwinc** [comment]
Closing this PR to include a more comprehensive one with other similar additions

**Pull request closed without merging**
